<?php

final class PhabricatorOauthserverDga
  extends PhutilTranslation {

  public function getLocaleCode() {
    return 'dga';
  }

  protected function getTranslations() {
    return array(
      'Log In with %s' => 'Kpɛ neŋ %s',
      'This application also requested additional unrecognized permissions. These permissions may have existed in an older version of the software, or may be from a future version of the software. They will not be granted.' => 'A aplikaaseŋ ŋa meŋ irikɔses la paaloo koŋ baŋ teɛre sori. A soe ŋa naŋ baŋ daŋ be la a vɛɛseŋ koroo sɔtwaɛ eŋɛ, bee na baŋ yi la a sɔtwaɛ niŋe vɛɛseŋ poɔ. Ba koŋ nyɛ sori.',
      'Do you want to authorize the external application "%s" to access your %s account data, including your primary email address?' => 'Fo boɔrɔ la ka fo ɔtoraazi a ɛtɛɛnal aplikaaseŋ "%s" na asɛses fo %s die daga dɛta, poɔ fo peramere eemail adrɛse?',
      'This application will no longer be able to access this server on your behalf.' => 'A aplikaaseŋ ŋa ko la baŋ tõɔ asɛses a sɛva ŋa fo yuori eŋɛ.',
      'This application ("%s") is authorized to use your %s credentials. Continue to complete the authentication workflow.' => 'A aplikaaseŋ ŋa ("%s") ba ko o la sori ka o na toŋ ne fo %s tontomboma. Kyoge a baare a ɔtentekaaseŋ wɛkfuloo.',
      'Really disable the %s OAuth application? Users will no longer be able to authenticate against it, nor access this server using tokens generated by this application.' => 'Irili ŋmaa a %s OAuth aplikaaseŋ? Tontonneba ko la baŋ tõɔ ɔtenteketkyaare o, bee asɛses sɛva ŋa ne tokiŋ gyɛnerete a aplikaaseŋ ŋa.',
    );
  }

}
