<?php

final class PhabricatorextCoreTr
  extends PhutilTranslation {

  public function getLocaleCode() {
    return 'tr';
  }

  protected function getTranslations() {
    return array(
  'Escalate' => 'Eskale et',
  'Next: %s' => 'Sonraki: %s',
  'Standard Phabricator.' => 'Standart Phabricator.',
  'Auto-generated release schedule details.' => 'Otomatik oluşturulan sürüm takvimi ayrıntıları.',
  'Consumer Token' => 'Kullanıcı anahtarı',
  'Merged' => 'Birleştirildi',
  'Unresolved code review comments: %d' => 'Çözülmemiş kod inceleme yorumları: %d',
  'Customize query in gerrit' => 'Gerrit\'te sorguyu özelleştir',
  'Cannot Lock Task' => 'Görev Kilitlenemez',
  'Deploy `%s` to %s Wikis.' => 'Dağıt `%s` %s Vikiye.',
  'Unknown objectType \'%s\'' => 'Bilinmeyen objectType \'%s\'',
  'You do not have permission to escalate tasks as security issues. This action can only be taken by authorized users.' => '',
  'Show related patches' => 'İlgili yamaları gösterin',
  'Related Links' => 'İlgili bağlantılar',
  'No deployments on fridays' => 'Cuma günleri dağıtım yok',
  'You must provide either a username or userPHID' => 'Kullanıcı adı veya userPHID sağlamak zorundasınız',
  'MediaWiki base URI is required.' => 'MediaWiki temel URI adresi gerekiyor.',
  'Unknown policies: %s' => 'Bilinmeyen politikalar: %s',
  'OAuth JWT nonce didn\'t match what we sent.' => 'OAuth JWT nonce eşleşmedi gönderdiğimizle.',
  'Protect as security issue' => 'Güvenlik sorunu olarak koru',
  'OAuth JWT iss didn\'t match expected server name' => 'OAuth JWT iss için beklenen sunucu adıyla eşleşmedi.',
  'Show verbose output.' => 'Ayrıntılı çıktıyı gösterin.',
  'OAuth JWT wasn\'t valid at this time' => '',
  'Any serious bugs affecting `%s` should be added as subtasks beneath this one.' => '',
  'If something is serious enough to warrant a rollback then you should bring it to the attention of deployers on the [[ https://www.mediawiki.org/wiki/Special:MyLanguage/MediaWiki_on_IRC | #wikimedia-operations IRC channel ]].' => '',
  'The username for whom transactions will be rolled back.' => '',
  'No "security" task subtype is defined in "maniphest.subtypes" in this installation. Please file a bug report.' => '',
  'ChangeId' => 'ChangeId',
  'Only admins can call this API' => 'Bu API\'yi sadece hizmetliler çağırabilir.',
  'OAuth provider returned an error response.' => 'OAuth provider returned an hata yanıt.',
  'Ensure Security Task Policies are Enforced' => '',
  'Release Details' => 'Çıkış Ayrıntıları',
  'This MediaWiki Train Deployment is scheduled for the week of' => '',
  'WIP - Work in Progress' => 'WIP - Süreç içerisindeki iş',
  'Query users by ldap username.' => 'Query kullanıcıs by ldap kullanıcıad.',
  'LDAP User' => 'LDAP kullanıcısı',
  'Related Changes in GitLab:' => 'GitLab\'daki İlgili Değişiklikler:',
  'Invalid action \'%s\'!' => 'Geçersiz eylem \'%s\'!',
  'Shows the gerrit Change ID for a commit.' => '',
  'MediaWiki' => 'MediaWiki',
  'MediaWiki Base URI' => 'MediaWiki Temel URI',
  'Execute searches for Policies.' => 'Politikalar için arama yap.',
  'Find public transactions by a particular user.' => '',
  'Skip OFFSET rows before processing the remaining transactions.' => '',
  'Execute a rollback.' => 'Geri döndürme işlemini yapın',
  '**Step 2 of 2**: Create a MediaWiki OAuth consumer for this Phabricator instance.

NOTE: Propose an OAuth 1.0a consumer with the form at this URL: %s

Provide the following settings on the consumer registration:

  - **OAuth "callback" URL:** Set this to: `%s`
  - **Allow consumer to specify a callback in requests and use "callback" URL above as a required prefix:** Enable this setting.
  - **Applicable grants:** `Basic Rights` is all that is needed for authentication.


After you register the consumer, a **Consumer Token** and consumer **Secret Token** will be provided to you by MediaWiki. To complete configuration of Phabricator, copy the provided keys into the corresponding fields above.

NOTE: Before Phabricator can successfully authenticate to your MediaWiki, a wiki admin must approve the OAuth consumer registration using the form which can be found at the following url: %s' => '',
  'Invalid' => 'Geçersiz',
  'Blocked on Code Review - Needs Changes' => '',
  'View Change in Gerrit' => 'Gerrit\'teki değişiklikleri inceleyin',
  'You must disable the user before rolling back their activity' => '',
  'Link to Open Tasks' => 'Açık görevlere bağla',
  'Secret Token' => 'Gizli Anahtar',
  'Secret Token is required' => 'Gizli Anahtar gereklidir',
  'Limit the number of transaction rows to process. Default: 10000' => 'İşlenecek işlem satırlarının sayısını ayarlayın. Varsayılan değer: 10000',
  'objectType is required.' => 'objectType gereklidir.',
  'Unknown or missing ldap names: %s' => 'Bilinmeyen veya eksik ldap adları: %s',
  'NOTE: Copy the keys generated by the MediaWiki OAuth consumer registration and paste them here.' => '',
  'Invalid rule class \'%s\'!' => 'Geçersiz kural sınıfı \'%s\'!',
  'Phabricator transaction rollback tool.' => '',
  'This task has no related gerrit patches.' => '',
  'Gerrit Patches' => 'Gerrit yamaları',
  'This task has no related GitLab merge requests.' => '',
  'Customize query in GitLab' => '',
  'You must provide either --user or --user-phid' => '',
  'For more info about deployment blockers, see [[ https://wikitech.wikimedia.org/wiki/Deployments/Holding_the_train | Holding the train ]].' => '',
  'Sort by Last Update' => 'Son güncellemeye göre sırala',
  'Consumer Token is required' => 'Consumer Token gerekli',
  '%s Line(s) removed' => '%s Satır kaldırıldı',
  'OAuth JWT aud didn\'t match expected consumer key' => '',
  'Code Review Started' => '',
  'Enable expert mode to reveal additional "advanced" options in the Phabricator UI.' => '',
  'OAuth error: Login failed because your MediaWiki account "%s" is blocked' => '',
  'Hide Instructions' => 'Talimatları gizle',
  '**Step 1 of 2**: Provide the name and URI for your MediaWiki install.

In the next step, you will create an OAuth consumer in MediaWiki to be used by Phabricator OAuth.' => '',
  'users subscribed to' => 'kullanıcılar şuraya abone oldu',
  'Execute a dry run, changes will not be writen back to the database.' => '',
  'Branch `%s` and deploy to %s Wikis.' => '',
  'No project tags "Security" and "Security-Team" exist in this installation. Please file a bug report.' => '',
  'Expert Mode.' => 'Uzman Modu.',
  'No project tag "acl*security" exists in this installation. Please file a bug report.' => '',
  'The specified username / userPHID was not found' => 'Belirtilen kullanıcı adı / userPHID bulunamadı',
  'See https://wikitech.wikimedia.org/wiki/Deployments for full schedule.' => '',
  'You cannot lock this task because it is already protected by a custom security policy.' => '',
  'Missing or malformed parameter.' => 'Eksik veya hatalı parametre.',
  'How this works' => 'Nasıl çalışır',
  'Create custom access control policy objects.' => '',
  'Use [[%s|this form]] to create one.' => '',
  'MediaWiki User' => 'MediaWiki Kullanıcısı',
  'Reset security settings' => 'Güvenlik ayarlarını sıfırla',
  'Open Tasks' => 'Görevleri Aç',
  'Unknown' => 'Bilinmiyor',
  '**MediaWiki Instance Name**

Choose a permanent name for this instance of MediaWiki. Phabricator uses this name internally to keep track of this instance of MediaWiki, in case the URL changes later.

Use lowercase letters, digits, and period. For example: 

`mediawiki`, `mediawiki.mycompany` or `mediawiki.engineering` are reasonable names.' => '',
  'Global Accounts' => 'Küresel Hesaplar',
  'Previous: %s' => 'Önceki: %s',
  'Query users by MediaWiki username.' => 'Query kullanıcıs by MediaWiki kullanıcıad.',
  'You cannot roll back the activity of a privileged user.' => '',
  'Any open subtask(s) block the train from moving forward. This means no further deployments until the blockers are resolved.' => '',
  'This adds a link to search Maniphest for open tasks which are tagged with this project. NOTE: This feature is provided by a Wikimedia-maintained extension in ProjectOpenTasksProfileMenuItem.php. See https://gitlab.wikimedia.org/repos/phabricator/extensions for the source.' => '',
  'The full URL to your MediaWiki install, up to but not including "index.php"' => '',
  'This panel shows navigation links to other milestones in the same series.' => '',
  'Expert Mode' => 'Uzman Modu',
  'Unknown or missing mediawiki names: %s' => 'Bilinmeyen veya eksik mediawiki adı: %s',
  'After reverting transactions, delete the reverted transaction records.' => '',
  'No Permission' => 'İzin Yok',
  'Required' => 'Gerekli',
  'Abandoned' => 'Terk edilmiş',
  '%s Line(s) added' => '%s Satır eklendi',
  'If you have a risky change in this week\'s train add a comment to this task using the {icon train spin}{icon fire color=red} [[ https://wikitech.wikimedia.org/wiki/Deployments/Risky_change_template | Risky patch template ]]' => '',
  'Comments' => 'Yorumlar',
);
  }

}
