<?php

final class PhabricatorMetamtaDa
  extends PhutilTranslation {

  public function getLocaleCode() {
    return 'da';
  }

  protected function getTranslations() {
    return array(
      'File PHID: %s' => 'Fil-PHID: %s',
      'External Recipient' => 'Ekstern modtager',
      'ID: %d' => 'ID: %s',
      'Message PHID' => 'Besked-PHID',
      'No Subject' => 'Intet emne',
      'Mail (Received)' => 'Mail (Modtaget)',
      'No Receivers' => 'Ingen modtagere',
      'Deliver as email' => 'Lever som e-mail',
      'Send an email to' => 'Send en e-mail til',
      'Outbox' => 'Udbakke',
      'Inbox' => 'Indbakke',
      'PARAMETERS' => 'PARAMETRE',
      'Deliver as email.' => 'Lever som e-mail.',
      'View Object' => 'Vis objekt',
      'Similar Reply' => 'Lignende svar',
      'Empty Mail' => 'Tom mail',
      'Send an email to: %s.' => 'Send en e-mail til: %s.',
      'Reserved' => 'Reserveret',
      'Unnamed File' => 'Ikke-navngivet fil',
      'Status: %s' => 'Status: %s',
      'Delete Address' => 'Slet adresse',
      'Mail (Sent)' => 'Mail (Sendt)',
      'PROPERTIES' => 'EGENSKABER',
      'Message: %s' => 'Besked: %s',
      'Attached Files' => 'Vedhæftede filer',
      'Subject' => 'Emne',
      'No attachments.' => 'Ingen vedhæfninger.',
      'Delivery' => 'Levering',
      'HEADERS' => 'OVERSKRIFTER',
      'Outbound Mail' => 'Udgående mail',
      'Attach a file.' => 'Vedhæft en fil.',
      'BODIES' => 'BRØDTEKSTER',
      'No Address' => 'Ingen adresse',
      'Sent by %s' => 'Sendt af Phabricator',
      'Generated by Server' => 'Genereret af Phabricator',
      'ATTACHMENTS' => 'VEDHÆFTNINGER',
      'Send mail again.' => 'Send mail igen.',
      'Delivery Failed' => 'Levering mislykkedes',
      'MESSAGE' => 'BESKED',
      '#' => '#',
      'Browse Email Addresses' => 'Gennemse emailadresser',
      'Unfiltered' => 'Ufiltreret',
      'This message was not delivered to you.' => 'Denne besked blev ikke leveret til dig.',
      'Unknown Sender' => 'Ukendt afsender',
      'RECIPIENTS' => 'MODTAGERE',
      '(No subject.)' => '(Intet emne.)',
      'Address "%s" is unknown.' => 'Adressen "%s" er ukendt.',
      'No sent mail.' => 'Ingen sendte mails.',
      'Delivered' => 'Leveret',
      'Address Not Verified' => 'Adressen er ikke bekræftet',
      'Send and Receive Mail' => 'Send og modtag e-mails',
      'Message Fields' => 'Beskedfelter',
      'Browse Subscribers' => 'Gennemse abonnenter',
    );
  }

}
